name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        sudo apt update
        sudo apt install gcc build-essential grub2-common grub-pc xorriso qemu-system-x86 xorriso mtools cpio
    - name: make
      run: make
    - name: run and test
      run: make clean && make && make test
